version = 1
[merge]
automerge_label = "automerge"
require_automerge_label = true
delete_branch_on_merge = true
notify_on_conflict = true
[merge.message]
title = "pull_request_title"
include_pull_request_url = true
include_pr_number = true 
[update]
require_automerge_label = true 
[approve]
auto_approve_usernames = ["lodmfjord"]
