compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

initScope: island.is

injectEnvironmentFiles:
  - .env.root?
  - .env?

nmMode: hardlinks-local

nodeLinker: node-modules

preferReuse: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs

npmScopes: { island.is: { npmRegistryServer: "https://npm.pkg.github.com" } }
