compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

initScope: island.is

injectEnvironmentFiles:
  - .env.root?

nmMode: hardlinks-local

nodeLinker: node-modules

preferReuse: true

packageExtensions:
  eslint-plugin-import-order-autofix@*:
    dependencies:
      ast-types: "*"
      babel-eslint: "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs
