name: Release

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ec2-runners
    if: |
      github.event.issue.user.login == 'andes-it' &&
      startsWith(github.event.issue.title, 'Release draft for version:') &&
      contains(fromJson(vars.RELEASE_MANAGERS), github.event.comment.user.login) &&
      startsWith(github.event.comment.body, 'release')
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    permissions: write-all
    steps:
      - name: Extract SHA from issue body
        id: extract-sha
        run: |
          SHA_REGEX="SHA: ([a-f0-9]+)"
          if [[ "${{ github.event.issue.body }}" =~ $SHA_REGEX ]]; then
            echo "SHA::${BASH_REMATCH[1]}"
            echo "SHA=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          fi
      - name: Echo SHA
        run: |
          echo ${{ env.SHA }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.PT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PIPES_ACTION: Release
          RELEASE_BODY: ${{ github.event.issue.body }}
        run: yarn node src/ci.tsx
        working-directory: ./ci
